### PR TITLE
Account activation background color fix

### PR DESCRIPTION
**Pull request by robotnicka**
Request to change the background-color for .content — on the account activation page, the content background was unstyled and displaying black text on a black background.

### CODE REVIEW

**Comment by robotnicka** [comment]
Picture for example: http://i.imgur.com/gpv9NFY.png

**Comment by ChaosExAnima** [comment]
@robotnicka - This would remove the color between the sidebar and content well, which I'm not too sure about. Can you provide the URL where things are broken?

**Comment by robotnicka** [comment]
@ChaosExAnima You're right that's no good, I missed that.
https://www.mindseyesociety.org/wp-activate.php  It's where users are taken
after clicking the account activation page through email.

Emily Mentrek
US2013100153

**Comment by ChaosExAnima** [comment]
Okay, so I think we can have something a bit more targeted here. I'll have to review that template, but it should be straightforward.

**Comment by ChaosExAnima** [comment]
Also, side note: PRs to this repo should update the Stylus and also compile to the CSS, so we don't have sync issues. If you're still having issues with that, we can talk.

**Comment by robotnicka** [comment]
@ChaosExAnima I was able to get stylus working. We don't commit the css
files that we compile at work. I didn't commit those out of habit. I'll add
them next time. Sorry :)

As for the template I do not have access to that, it's outside of the
themes folder. There's no rush.

Emily Mentrek
US2013100153

**Comment by ChaosExAnima** [comment]
@robotnicka - Closing this. I put up a fix that directly targets the page instead.

**Comment by robotnicka** [comment]
@ChaosExAnima you're the best!!

Emily Mentrek
US2013100153

**Pull request closed without merging**
