### PR TITLE
Css alterations

### PR DESCRIPTION
**Pull request by robotnicka**
Couple suggested changes for css. Most important one would be the latest (236aa7f) where the page-button visited link color does not change.

### CODE REVIEW

**Comment by ChaosExAnima** [comment]
@robotnicka - Please merge master. It should remove the CSS changes and leave the image.

**Comment by robotnicka** [comment]
Merged into master. I'm hoping that was what you were looking for. Still getting used to git. :)

**Comment by ChaosExAnima** [comment]
Okay, looks like the CSS file is now a duplicate, as `h3` is repeated twice. Why the photo, @robotnicka?

**Comment by robotnicka** [comment]
@ChaosExAnima the photo would be for the background of the site itself. It's pulled directly from the existing site. Sorry about the css dup, not sure why that happened! I haven't really done much with forking at all, and it's still kind of new to me.

**Comment by ChaosExAnima** [comment]
@robotnicka Okay. Where's it going to be loaded? If we need to 100% replicate that background, I'm more inclined to make it part of the WP Customizer, so we can change it per site instead of hardcoding it.

**Comment by robotnicka** [comment]
That's fine with me. I plan on making separate banners for each of the
multisites as well. I don't want to make the visual style of each of the
multisites look too drastic, but having a slight change on each to tell the
user where they are would be nice. Being able to change the background
through the customizer for each site would be useful. Thanks!

Emily Mentrek
US2013100153

**Comment by ChaosExAnima** [comment]
Cool. I'm closing this PR as implemented.

**Pull request closed without merging**
